HW 3. JavaScript primitive data types
viaylya1/aqa-advanced pull request #4
Opened 2024-01-23 20:02 UTC by viaylya1

2024-01-23 21:26 UTC, sttaran requested changes

2024-01-23 21:26 UTC, sttaran commented on jsBasics/task1.js
> +let hasCar = true;
use `const`

2024-01-23 21:26 UTC, sttaran commented on jsBasics/task1.js
> +let lastName = "Bryzhak";
use `const`

2024-01-23 21:26 UTC, sttaran commented on jsBasics/task3.js
> +let personAge = 14;
use `const`

2024-01-23 21:26 UTC, sttaran commented on jsBasics/task4.1.js
> +let areaOfCircle = (Math.PI * Math.pow(radius, 2)).toFixed(2);
use `const`

2024-01-24 21:41 UTC, viaylya1 commented on jsBasics/task1.js
> +let hasCar = true;
fixed

2024-01-24 21:41 UTC, viaylya1 commented on jsBasics/task1.js
> +let lastName = "Bryzhak";
fixed

2024-01-24 21:41 UTC, viaylya1 commented on jsBasics/task3.js
> +let personAge = 14;
fixed

2024-01-24 21:42 UTC, viaylya1 commented on jsBasics/task4.1.js
> +let areaOfCircle = (Math.PI * Math.pow(radius, 2)).toFixed(2);
fixed

2024-01-24 22:19 UTC, sttaran approved these changes

2024-01-25 07:52 UTC, merged